update: all
pin: True
branch: master
schedule: "every day"
search: False

requirements:
  - requirements/base.txt
  - requirements/local.txt
  - requirements/production.txt

branch_prefix: pyup-
close_prs: True
