dist: xenial

language: python
python:
  - "3.8"

services:
  - docker
jobs:
  include:
    - name: "Linter"
      before_script:
        - pip install -q flake8
      script:
        - "flake8"

    - name: "Django Test"
      before_script:
        - echo ${DOCKER_ACCESS_TOKEN} | docker login --username ${DOCKER_USERNAME} --password-stdin
        - docker-compose -v
        - docker -v
        - docker-compose -f local.yml build
        # Ensure celerybeat does not crash due to non-existent tables
        - docker-compose -f local.yml run --rm django python manage.py migrate
        - docker-compose -f local.yml up -d
      script:
        - "docker-compose -f local.yml run django pytest"
      after_failure:
        - docker-compose -f local.yml logs
