sudo: required
language: python
python:
  - "3.6"
services:
  - docker
before_script:
  - docker-compose -f production.yml build
script:
  - docker-compose run --rm django bash -c "flake8 && python manage.py test"
cache:
  pip: true
