name: Lint

on:
  - push
  - pull_request

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8
